name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.set_sha.outputs.short_sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Short sha
        id: set_sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true

          tags: ${{ secrets.DOCKER_USERNAME }}/python-app:${{ steps.set_sha.outputs.short_sha }}
      
  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infrastructure Repo
        uses: actions/checkout@v3
        with:
          repository: abhishekengg24/infra-repo
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          path: infra-repo

      - name: Update Image Tag in Helm Values
        run: |
          cd infra-repo
          # usig the short SHA passed from the previous jobs
          yq -i ".image.tag = \"${{ needs.build-and-push.outputs.short_sha }}\"" helm-charts/python-app/values.yaml


      - name: Commit and Push to Infra Repo
        run:  |
          cd infra-repo
          git config user.name "GitHub Actions"
          got config user.email "actions@github.com"
          git add .
          git commit -m "Deploying image tag ${{ needs.build-and-push.outputs.short_sha }}"
          git push